{
 "title": "PV-Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Gruppierung", "label": "Gruppierung in Langzeitgraphen", "query": "1d,1w,30d,1y" },
   {
    "name": "rp",
    "label": "Retention Policy",
    "query": "select rp from forever.rp_config where time >= now() - ${__from}ms order by time asc limit 1"
   },
   { "name": "strompreis", "query": "0.2941" },
   { "name": "verguetung", "query": "0.0854" },
   { "name": "kapazitaet", "label": "Batteriekapazität", "query": "7680" }
  ]
 },
 "panels": [
  { "title": "Aktuelle Werte und  Tageswerte", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV Leistung",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "2d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(total_dc_power) FROM mqtt_consumer  fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netz Leistung",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "2d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(export_power_hybrid) FROM mqtt_consumer fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(load_power_hybrid) FROM mqtt_consumer fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicher Lade-/Entladeleistung",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "2d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(battery_power) * last(state_battery_charging) FROM mqtt_consumer fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicher SoC ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "2d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(battery_level) FROM mqtt_consumer fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Ertrag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(daily_pv_generation) FROM mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netzeinspeisung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(daily_pv_export) FROM mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(export_power_hybrid) FROM mqtt_consumer WHERE time > now()-1d group by time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Direktverbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(daily_direct_energy_consumption) FROM mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speicher Laden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(daily_battery_charge_from_pv) FROM mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zeit bis vollst. Ent-/Ladung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Entladung",
     "query": "SELECT $kapazitaet * battery_level / 100 * 3600 / battery_power  FROM (SELECT last(battery_level) as battery_level, last(battery_power) as battery_power, last(battery_voltage) as battery_voltage, last(battery_current) as battery_current, last(state_battery_discharging) as battery_discharging FROM mqtt_consumer) where  battery_discharging = 1"
    },
    {
     "alias": "Ladung",
     "query": "SELECT ($kapazitaet - $kapazitaet * battery_level / 100) * 3600 / battery_power  FROM (SELECT last(battery_level) as battery_level, last(battery_power) as battery_power, last(battery_voltage) as battery_voltage, last(battery_current) as battery_current, last(state_battery_charging) as battery_charging FROM mqtt_consumer) where  battery_charging = 1"
    }
   ]
  },
  {
   "title": "Speicher Entladen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(daily_battery_discharge_energy) FROM mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netzbezug",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(daily_import_energy) FROM mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(battery_power) * last(state_battery_charging) FROM mqtt_consumer WHERE time > now()-1d group by time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(daily_direct_energy_consumption) + last(daily_battery_discharge_energy) + last(daily_import_energy) FROM mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Autarkiegrad",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "query": "SELECT (hausverbrauch - netzbezug) / hausverbrauch * 100 from (SELECT (last(daily_direct_energy_consumption) + last(daily_battery_discharge_energy) + last(daily_import_energy)) as hausverbrauch, last(daily_import_energy) as netzbezug FROM mqtt_consumer WHERE $timeFilter GROUP BY time($__interval))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate" }
     ]
    }
   ]
  },
  {
   "title": "Eigenverbrauchsgrad",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "query": "SELECT (PV - Netzeinspeisung) / PV * 100 FROM (SELECT last(daily_pv_generation) as PV, last(daily_pv_export) as Netzeinspeisung FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate" }
     ]
    }
   ]
  },
  {
   "title": "Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(load_power_hybrid), time FROM mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(system_state) FROM mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spannung",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "SELECT last(battery_voltage) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)"
      }
     ]
    },
    {
     "title": "Strom",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "SELECT last(battery_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)"
      }
     ]
    },
    {
     "title": "Berechnete Leistung",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "SELECT last(battery_voltage) * last(battery_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval)  fill(previous)"
      }
     ]
    },
    {
     "title": "Gesundheit",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "SELECT last(battery_state_of_healthy) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(previous)"
      }
     ]
    },
    {
     "title": "Speicher laden",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_battery_charge_from_pv) FROM forever.mqtt_consumer ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Speicher entladen",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_battery_discharge_energy) FROM forever.mqtt_consumer ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Ladezyklen",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_battery_charge_from_pv) * 1000 / $kapazitaet FROM forever.mqtt_consumer ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Wirkungsgrad",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_battery_discharge_energy) / last(total_battery_charge_from_pv) * 100 FROM forever.mqtt_consumer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gesamtwerte",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "PV Ertrag",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_pv_generation) FROM forever.mqtt_consumer fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Netzeinspeisung",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_pv_export) FROM forever.mqtt_consumer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Direktverbrauch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "alias": "PV",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_direct_energy_consumption) FROM forever.mqtt_consumer ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Netzbezug",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_import_energy) FROM forever.mqtt_consumer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Hausverbrauch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT last(total_direct_energy_consumption) + last(total_battery_discharge_energy) + last(total_import_energy) FROM forever.mqtt_consumer ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Autarkiegrad",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "mqtt_consumer",
       "query": "SELECT (hausverbrauch - netzbezug) / hausverbrauch * 100 from (SELECT (last(total_direct_energy_consumption) + last(total_battery_discharge_energy) + last(total_import_energy)) as hausverbrauch, last(total_import_energy) as netzbezug FROM forever.mqtt_consumer)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "openwb" }
       ]
      }
     ]
    },
    {
     "title": "Eigenverbrauchsgrad",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "30m" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "solcast",
       "query": "SELECT (PV - Netzeinspeisung) / PV * 100 FROM (SELECT last(total_pv_generation) as PV, last(total_pv_export) as Netzeinspeisung FROM forever.mqtt_consumer)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 2" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "pv_estimate" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Detailgraph Allgemein", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PV Leistung, PV-Prognose, Sonnenstand, Netz Leistung, Speicherleistung, Speicher SoC und Hausverbrauch",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "PV-Leistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(total_dc_power) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "total_dc_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netz-Leistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(export_power_hybrid) * -1 FROM $rp.mqtt_consumer WHERE export_power_hybrid < 0 AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(load_power_hybrid) from $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV-Prognose",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "solcast",
     "query": "SELECT mean(pv_estimate) FROM forever.solcast WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "pv_estimate" }
     ]
    },
    {
     "alias": "Speicher-Laden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(battery_power) FROM $rp.mqtt_consumer WHERE state_battery_charging = 1 AND $timeFilter GROUP BY time(30s) fill(0)",
     "select": [
      [
       { "params": [ "battery_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher-Entladen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(battery_power)  FROM $rp.mqtt_consumer WHERE state_battery_discharging = 1 AND $timeFilter GROUP BY time(30s) fill(0)",
     "select": [
      [
       { "params": [ "battery_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Überschuss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(export_power_hybrid) FROM $rp.mqtt_consumer WHERE export_power_hybrid > 0 AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher-SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(battery_level) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "Detailgraphen Aufteilung Hausverbrauch und PV-Erzeugung",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Aufteilung Hausverbrauch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(export_power_hybrid) * -1 FROM $rp.mqtt_consumer WHERE export_power_hybrid < 0 AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher entladen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(battery_power) FROM $rp.mqtt_consumer WHERE battery_discharging = 1 AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(load_power_hybrid) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aufteilung PV-Ertrag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Netzeinspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(export_power_hybrid) FROM $rp.mqtt_consumer WHERE export_power_hybrid > 0 AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher laden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(battery_power) FROM $rp.mqtt_consumer WHERE state_battery_charging = 1 AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV-Ertrag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(total_dc_power)  FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "MPPT-Spannung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "MPPT 1 Spannung",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(mppt_1_voltage) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MPPT 2 Spannung",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(mppt_2_voltage) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MPPT 1 Strom",
     "query": "SELECT mean(mppt_1_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "MPPT 2 Strom",
     "query": "SELECT mean(mppt_2_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "MPPT-Leistung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(total_dc_power) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MPPT 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(mppt_1_current) * mean(mppt_1_voltage) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MPPT 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(mppt_2_current) * mean(mppt_2_voltage)  FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MPPT 1 + MPPT 2",
     "query": "SELECT mean(mppt_1_current) * mean(mppt_1_voltage) + mean(mppt_2_current) * mean(mppt_2_voltage) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "PV-Ertrag und Prognose (Gruppierung über Variable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "PV-Ertrag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(daily_pv_generation) FROM (SELECT max(daily_pv_generation) as daily_pv_generation FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV-Prognose",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value2) from (SELECT sum(value1) /1000 as value2 from (SELECT mean(pv_estimate)  / 2 as value1 FROM forever.solcast WHERE $timeFilter GROUP BY time(30m) fill(0)) WHERE $timeFilter GROUP by time(1d)) WHERE $timeFilter GROUP BY time($Gruppierung)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aufteilung PV-Ertrag (Gruppierung über Variable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "PV-Leistung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(daily_pv_generation) FROM (SELECT max(daily_pv_generation) as daily_pv_generation FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzeinspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(daily_pv_export) FROM (SELECT max(daily_pv_export) as daily_pv_export FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher Laden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(daily_battery_charge_from_pv) FROM (SELECT max(daily_battery_charge_from_pv) as daily_battery_charge_from_pv FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Hausverbrauch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Hausverbrauch (Gruppierung über Variable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM (SELECT (max(daily_direct_energy_consumption) + max(daily_battery_discharge_energy) + max(daily_import_energy)) as value FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aufteilung Hausverbrauch (Gruppierung über Variable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(daily_import_energy) FROM (SELECT max(daily_import_energy) as daily_import_energy FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher Entladen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(daily_battery_discharge_energy) FROM (SELECT max(daily_battery_discharge_energy) as daily_battery_discharge_energy FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT sum(value) FROM (SELECT (max(daily_direct_energy_consumption) + max(daily_battery_discharge_energy) + max(daily_import_energy)) as value FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Temperatur", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Speicher",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(battery_temperature) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wechselrichter",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(internal_temperature) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Speicher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Speicher Laden/Entladen und durchschnittlicher Max-/Min-SoC (Gruppierung über Variable)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "durchschnittlicher Max-SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(battery_level) FROM (SELECT max(battery_level) as battery_level FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "durchschnittlicher Min-SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(battery_level) FROM (SELECT min(battery_level) as battery_level FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speicher Laden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(daily_battery_charge_from_pv) FROM (SELECT max(daily_battery_charge_from_pv) as daily_battery_charge_from_pv FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*(-1)" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Speicher Entladen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(daily_battery_discharge_energy) FROM (SELECT max(daily_battery_discharge_energy) as daily_battery_discharge_energy FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lade-/Entladekurve",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "SELECT  mean(battery_power) * mean(state_battery_charging) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  { "title": "Netz", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }, "repeat": "topicsEvuCurrent" },
  {
   "title": "Bezug/Einspeisung (Gruppierung über Variable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Netzeinspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(daily_pv_export) FROM (SELECT max(daily_pv_export) as daily_pv_export FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(daily_import_energy) FROM (SELECT max(daily_import_energy) as daily_import_energy FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netz-Spannung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Phase 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_a_voltage) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Phase 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_b_voltage) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Phase 3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_c_voltage) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(10s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Blindleistung",
     "query": "SELECT mean(total_reactive_power) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Netz-Strom",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Phase 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_a_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Phase 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_b_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Phase 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_c_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzfrequenz",
     "query": "SELECT mean(grid_frequency) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Netz-Leistung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Phase 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_a_voltage) * mean(phase_a_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Phase 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_b_voltage)  * mean(phase_b_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Phase 3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(phase_c_voltage)  * mean(phase_c_current) FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(10s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eigenverbrauchs- und Autarkiegrad",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 }
  },
  {
   "title": "Eigenverbrauch und Autarkie (Gruppierung über Variable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM (SELECT (max(daily_direct_energy_consumption) + max(daily_battery_discharge_energy) + max(daily_import_energy)) as value FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(daily_import_energy) FROM (SELECT max(daily_import_energy) as daily_import_energy FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time($__interval) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(daily_pv_generation) FROM (SELECT max(daily_pv_generation) as daily_pv_generation FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzeinspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(daily_pv_export) FROM (SELECT max(daily_pv_export) as daily_pv_export FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ersparnis- und Einnahmenrechner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 }
  },
  {
   "title": "Ersparnis und Einnahmen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (last(total_direct_energy_consumption) + last(total_battery_discharge_energy)) * $strompreis +  last(total_pv_export) * $verguetung FROM forever.mqtt_consumer "
    }
   ]
  },
  {
   "title": "Ersparnis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Ersparnis",
     "query": "SELECT (last(total_direct_energy_consumption) + last(total_battery_discharge_energy)) * $strompreis FROM forever.mqtt_consumer "
    }
   ]
  },
  {
   "title": "Einnahmen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Einspeisung",
     "query": "SELECT last(total_pv_export) * $verguetung FROM mqtt_consumer"
    }
   ]
  },
  {
   "title": "Kosten",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Netzbezug",
     "query": "SELECT last(total_import_energy) * $strompreis   FROM mqtt_consumer"
    }
   ]
  },
  {
   "title": "Ersparnis und Einnahmen (Gruppierung über Variable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "alias": "Hausverbrauch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value)*$strompreis FROM (SELECT (max(daily_direct_energy_consumption) + max(daily_battery_discharge_energy) + max(daily_import_energy)) as value FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Netzbezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value)*$strompreis  FROM (SELECT max(daily_import_energy) as value FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Einnahmen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) * $verguetung FROM (SELECT max(daily_pv_export) as value FROM $rp.mqtt_consumer WHERE $timeFilter GROUP BY time(1d) fill(0)) GROUP BY time($Gruppierung) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 } },
  {
   "title": "System state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT system_state FROM $rp.mqtt_consumer WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}